baseurl = "https://example.org/"
languageCode = "en-us"
title = "Katie's Data Science Blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Katie Reisinger"
    site_description = "Quick R Tutorials"
    location = "Mercyhurst University"
    # Link custom assets relative to /static
    avatar = "llama2.png"
    header_background = "mountains.jpg"
    header_title = "Katie's Data Science Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    facebook  = "https://www.facebook.com/katie.reisinger.52"
    linkedin  = "https://www.linkedin.com/in/katherine-reisinger-3195a8126/"
    github    = "https://github.com/kreisi62"
